"""Remove created_at from user tables at 2025-04-02 13:42:35 by InvictusRex

Revision ID: c90c279c986d
Revises: 2389c704e5be
Create Date: 2025-04-02 19:14:18.825424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c90c279c986d'
down_revision: Union[str, None] = '2389c704e5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'created_at')
    op.drop_column('doctors', 'created_at')
    op.drop_column('patients', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('doctors', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('admins', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
